### ISSUE TITLE
About the source code

### ISSUE THREAD

**Issue by mobeixiaoxin** [lingtengqiu/OPEC-Net#1]
Hello，thanks for the great work!
I want to learn the structure of the work，but my code ability is limited， so I want to know when the source code would be publiced?
Thank you!

**Comment by lingtengqiu** [comment]
I would release this demo code before November. thanks for your attention





------------------ Original ------------------

**Comment by mobeixiaoxin** [comment]
thanks!!!

**Comment by WinstonDeng** [comment]
@lingtengqiu Hi, when the source code would be publiced?
