### ISSUE TITLE
A question about the code for ResGCN

### ISSUE THREAD

**Issue by ArchNew** [lingtengqiu/OPEC-Net#10]
According to the paper "DeepGCN," the first step is to use the current node's features to subtract all its neighbors and find the maximum of those results.
In your code, I can find all other steps regarding the ResGCN module described in the paper, but I can't seem to find this "first step."

**Comment by lingtengqiu** [comment]
We do not use the implementation of deep GCN. For more details, you could download the supplementary of paper. Thanks

**Comment by ArchNew** [comment]
The supplementary materials directly after the end of the paper refers to the GCN layers within the ResGCN to the DeepGCN paper. Unless you have other supplementary material that I'm unaware of, I can't find any details about those GCN layers.

If there are other supplementary materials, may I ask where could I download them?

**Comment by ArchNew** [comment]
I'm happy to report that with minor modification, it's rather easy to turn your GCN module to deepgcn version. Your code has done most of the work, I only need to add the "first step" I mentioned.
