### ISSUE TITLE
About the Semantic Graph Convolution, where can I read the paper about it?

### ISSUE THREAD

**Issue by ArchNew** [lingtengqiu/OPEC-Net#11]
It seems your paper doesn't contain the details about the semantic graph conv. After carefully reading your codes, I find that your ResGCN module is basically a BasicBlock of the ResNet plus a SENet layer. I'm very much curious about the invention of this GCN module. Could you kindly point me to the paper that invented this module?

**Comment by lingtengqiu** [comment]
you can reference to https://github.com/garyzhao/SemGCN.
