### ISSUE TITLE
I have a question regarding to train your model end-to-end.

### ISSUE THREAD

**Issue by ArchNew** [lingtengqiu/OPEC-Net#12]
I'm aware that the training schedules you offered here only include the GCN part. With a minor modification, it's not hard to do end-to-end training.

My question is, should I pre-train the FastPose part with integral regression? Or just load the official FastPose weights and train the model end-to-end according to the training schedule in your paper? If I need to pre-train the FastPose part, what kind of training schedule should I follow?

**Comment by lingtengqiu** [comment]
To be honest, you could modify my codes to end-to-end training. Considering GPU limitation, we could not offer the version that you could end-to-end train. Alternatively, first, you could filter training datasets according to the number of annotation joints(e.g. 50%) ,second, you employ awesome pose estimators(e.g. Alphapose) to produce x,y. Note that the results of Alphapose are inferened from heatmap-based methods, therefore you need chaneg heat map to intergral or fc layer.  after that you could end-to-end training my framework.

**Comment by ArchNew** [comment]
Thanks. From your answer, I gather the underperformance of integral regression won't be a big issue during the end-to-end training. It will finally be corrected by the GCN part of your model. Right?
