### ISSUE TITLE
I can't find the CoupleGraph part  in your code.

### ISSUE THREAD

**Issue by ArchNew** [lingtengqiu/OPEC-Net#13]
I'm interested in how do you define the "couple" instances in an image. Unfortunately, it seems I can't find it in your current code. If that part hasn't been released, do you plan to release it? If not, could you reveal the details of the CoupleGraph, so that we, who are interested in it, could implement that part on our own?

**Comment by lingtengqiu** [comment]
I will release couple-graph version soon. Now, I am busy studying courses :(, so please wait.

**Comment by ArchNew** [comment]
Thanks! Sorry to bother you. I'm sure you'll do excellent at all your courses. :D
