### ISSUE TITLE
The pre-trained model you employed is pre-trained on what? COCO? or both?

### ISSUE THREAD

**Issue by ArchNew** [lingtengqiu/OPEC-Net#14]
If I understand the code right, you train your model on both coco and crowdpose. So, I'm curious about the pre-trained mole, does it pre-trained on both datasets?

**Comment by lingtengqiu** [comment]
For fair comparision， I provide a quickly start version train on coco and crowdpose to have easily access to reimplementation of results. By the way，Happy new year， you are to diligent. you could put down email，we could contact through email：）







------------------ Original ------------------

**Comment by ArchNew** [comment]
Thanks. I'm sorry to bother you again and again. I'm new in research. It is well understood that occlusion can't be solved by extracting more features from the image. In more areas, such as optic flow, segmentation, they either go around it or use the "erasing" technic to boost the results. Your paper opens a new world to all the researchers in solving occlusion problems, not just researchers in pose estimation. It also opens my mind in related areas. Your work also proves that even though directly regress the coordinates isn't preferable in traditional pose estimation, it still can be helpful as a part of an end-to-end network. I also want to use graph net to do something in the pose, but the way of getting coordinates from heatmaps stands in my way. I don't have the nerve (or your deep understanding of the subject) to regress the coordinates directly as part of my design, especially I know its unflattering performance.

**Comment by ArchNew** [comment]
I'm sorry that I don't know how to leave a private message to give you my email or WeChat number. :(

**Comment by lingtengqiu** [comment]
> 
> 
> I'm sorry that I don't know how to leave a private message to give you my email or WeChat number. :(

Hi my email is 1259738366@qq.com
