### ISSUE TITLE
CrowdPose part

### ISSUE THREAD

**Issue by hongsukchoi** [lingtengqiu/OPEC-Net#15]
Hi, I saw the paper and it says that OPEC-Net uses the output of CrowdPose (=AlphaPose+) as an initial pose.
But I can't find the global association part of CrowdPose in this repository. 

More importantly, I'm curious about from which pose estimator do you extract features? CrowdPose leverages multiple 'joint-candidate SPPE', and outputs each final pose per each target person after global association. It means that the final joint locations of each person might be aggregated from multiple SPPEs. For example, a hip joint location of a target person might be estimated  from one SPPE, and an ankle joint location estimated from another SPPE. 
So I want to know the pose estimator that encodes images feature maps for 'Image-Guided Progressive GCN'.
Or are you just using AlphaPose, not CrowdPose?

Thanks in advance!

**Comment by lingtengqiu** [comment]
Thanks for you attention. Actually, we just use the alphapose+(based on pytorch, remain best-match post-processing), which has some differents from paper(according to the author says). In fact, you could employ varities of top-down estimator before Opec-net, which means the key of Opec-net do not depend on initial pose but whole framework.

**Comment by hongsukchoi** [comment]
I really appreciate your prompt answer. So the official code of CrowdPose is different with their paper :(. 

One more question.
Do you have any plan to add Couple Graph code in near future?
And I want to know whether Baseline+Couple Graph is better than OPEC-net. 
<img width="823" alt="스크린샷 2021-01-15 16 57 05" src="https://user-images.githubusercontent.com/31090011/104697171-b45f2080-5752-11eb-9968-2ce9f0933a80.png">

I think the description in your paper is little ambiguous on this. Does the last row method (denoted as Couple Graph) indicates Baseline+Couple Graph or OPEC-net+Couple Graph?

**Comment by lingtengqiu** [comment]
Yes, I plan to release the code related with Couple-Graph soon. In fact, the performance of Couple-Graph version is not better than single-graph one in many datasets(like Crowdpose, Ochuman datasets). However, In our dataset(OCPose), the improvement of the result of C-G is obvious. I think the reason is that our img colleted are built by couple scenarios. 

the couple graph indicates OPEC-net+Couple Graph :).
good luck

**Comment by hongsukchoi** [comment]
Thank you!
