### ISSUE TITLE
Train Test split of OCPose Dataset

### ISSUE THREAD

**Issue by rawalkhirodkar** [lingtengqiu/OPEC-Net#16]
Thank you for the great work.

Are the train:val:test splits available? 
I can only find the annot_all.json which contains all the annotations.

**Comment by lingtengqiu** [comment]
sorry, I will release it soon.

**Comment by rawalkhirodkar** [comment]
Hi, Any update on this?
Thanks.

**Comment by lingtengqiu** [comment]
Sorry I forget it，I will push the &nbsp;annotation list on Monday：）





------------------ Original ------------------

**Comment by rawalkhirodkar** [comment]
Thank you so much :)
Commenting as a reminder.

**Comment by lingtengqiu** [comment]
Hi， I already have submitted train_list and test_list.txt in github, good luck for u

**Comment by rawalkhirodkar** [comment]
Thank you.

I found that the uploaded train:test split is 7200:1800 images, which is not the same as the one reported in the paper train:val:test 5000:2000:2000.

Is it possible to get consistent splits?
Thanks again.
