### ISSUE TITLE
Could you provide your trained model and processed data on OCPose dataset? 

### ISSUE THREAD

**Issue by ArchNew** [lingtengqiu/OPEC-Net#22]
Since you didn't offer a train/val split, I'm wondering if your OCPose dataset merely a validation set?

**Comment by lingtengqiu** [comment]
I




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lingtengqiu/OPEC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上10:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lingtengqiu/OPEC-Net] Could you provide your trained model and processed data on OCPose dataset?  (#22)





 
Just like the one you provided on crowdpose dataset

**Comment by lingtengqiu** [comment]
I split train/val dataset, which are written down in train_list.txt and test_list.txt

**Comment by lingtengqiu** [comment]
I am afraid not, but it is easy that you could straightforwardly&nbsp; process data as paper said.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lingtengqiu/OPEC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上10:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lingtengqiu/OPEC-Net] Could you provide your trained model and processed data on OCPose dataset?  (#22)





 
Just like the one you provided on crowdpose dataset

**Comment by ArchNew** [comment]
Thanks for your answer. I found that the dataset is specific for pairs. It's less useful for me than I expected.
