### ISSUE TITLE
Results for constructing the graph

### ISSUE THREAD

**Issue by YibinXie** [lingtengqiu/OPEC-Net#7]
Why you use dts from the pose_generater to construct the graph node feature?
Why not just use heat_map_intergral result in the forward function of SemGCN_FC?
![image](https://user-images.githubusercontent.com/18461749/101739145-1a2c0d00-3b02-11eb-892d-5302ae2ede80.png)
@lingtengqiu

**Comment by lingtengqiu** [comment]
Thanks for your attentions. this is because we  find that the result of pose generator are more useful for training on the one hand. On the other hand, the purpose of heat_map_intergral is provided features that gap the domain between pose_generator and gcns.

**Comment by lingtengqiu** [comment]
Thanks for your attentions. this is because we find that the result of pose generator are more useful for training on the one hand. On the other hand, the purpose of heat_map_intergral is provided features that bridge the domain between pose_generator and gcns.

**Comment by YibinXie** [comment]
> Thanks for your attentions. this is because we find that the result of pose generator are more useful for training on the one hand. On the other hand, the purpose of heat_map_intergral is provided features that bridge the domain between pose_generator and gcns.

 @lingtengqiu
I think it's a great work and really inspiring.

Q1: Sorry, I'm a little confused. I think _hm_4_ and _out_ have similar results. So why out is more useful for training and why hm4 can bridge the gap?

Q2: By the way, what do you mean by the gap. Does it refer to the difference between the 2d domain and the graph domain?

Q3: What does the _dts_ stand for? Could elaborate on its dimensions?

Q4: Reading your code, I find that it seems you don't use end-to-end training for the approach. I think you just train the GCN part with the pose generator just inferring. It appears to be different from what you write in your paper. Coud I have your thoughts on this operation?

Sorry for all these trivial questions. Looking forward to your reply. Thanks in advance.

Regards and thanks,
Yibin

**Comment by lingtengqiu** [comment]
用中文说也许会更详细一点吧。
Q1：hm_4 和out 的结果肯定是不一样的，但是他们的空间维度是一样的，你可以将hm4的结果算一下他的mAP，hm_4（对比结果是65.0 几和70.6）提供了一个监督对他的特征空间，因为我们给gcn 的输入是xy和一个特征空间的feature，因此他们可以一起参与训练来使得特征空间一致。
Q2：这个gap 是指pose generator 的输出dts 和 GCN的特征空间 使得他一致。
Q3：你可以跑我的代码看下，在输入维度上设断点，看下dts 的维度for example （bs，node，2）->(x,y)

**Comment by lingtengqiu** [comment]
用中文说也许会更详细一点吧。
Q1：hm_4 和out 的结果肯定是不一样的，但是他们的空间维度是一样的，你可以将hm4的结果算一下他的mAP，hm_4（对比结果是65.0 几和70.6）提供了一个监督对他的特征空间，因为我们给gcn 的输入是xy和一个特征空间的feature，因此他们可以一起参与训练来使得特征空间一致。
Q2：这个gap 是指pose generator 的输出dts 和 GCN的特征空间 使得他一致。
Q3：你可以跑我的代码看下，在输入维度上设断点，看下dts 的维度for example （bs，node，2）->(x,y)
Q4: 这个是个快速的quick start版本，考虑到完全让pose generator 和 opec-net 联合起来的gpu 消耗是很大的。你可以改成一起训练没有问题。实际上我们说的训练的确是e2e的重整个pipeline 来看。
感谢你的关注，有机会的话一些技术细节可以当面讨论.

**Comment by YibinXie** [comment]
谢谢，有一些细节我在仔细看看代码尝试吧。
如果方便地话，希望能通过邮箱与你交流，在论文中没有看到你的邮箱，是否可以留个邮箱呢？
我的邮箱是ybxie97@foxmail.com
