### ISSUE TITLE
how to generate the dts

### ISSUE THREAD

**Issue by zlmo** [lingtengqiu/OPEC-Net#8]
Hello, thanks for your code. I have a question aboud the 'gts'.  How the gts generated in annotation file?  Use Alphapose generate headmaps and then apply soft-argmax on the heatmaps?

Tnanks.

**Comment by lingtengqiu** [comment]
I don't know what you want to know? 'gts' are  ground truth of human pose annotated by human e.g. coco annotations. According to our paper, we sample the training dataset if the visible threshold larger than t, where t is the percentage of joints are visible e.g. 40%.

**Comment by zlmo** [comment]
Sorry, I mean the  'dts'. I want to reimplement the model in mmpose, but can't  figure out how the 'dts' generated.

**Comment by lingtengqiu** [comment]
All right. One way to produce 'dts' is that you could inference the results of poses by awesome pose generators e.g. OpenPose, Alphapose and so on (The format of results: x, y ,score). By the way, I am a big fan of mmdetection :).

**Comment by zlmo** [comment]
Ok, thanks.
